package ru.lakeev.companyandstaff.name;

public enum FemaleName {
  FEM_NAME_0("София"),
  FEM_NAME_1("Софья"),
  FEM_NAME_2("Анастасия"),
  FEM_NAME_3("Дарья"),
  FEM_NAME_4("Дарина"),
  FEM_NAME_5("Мария"),
  FEM_NAME_6("Анна"),
  FEM_NAME_7("Виктория"),
  FEM_NAME_8("Полина"),
  FEM_NAME_9("Елизавета"),
  FEM_NAME_10("Екатерина"),
  FEM_NAME_11("Ксения"),
  FEM_NAME_12("Валерия"),
  FEM_NAME_13("Варвара"),
  FEM_NAME_14("Александра"),
  FEM_NAME_15("Вероника"),
  FEM_NAME_16("Арина"),
  FEM_NAME_17("Алиса"),
  FEM_NAME_18("Алина"),
  FEM_NAME_19("Милана"),
  FEM_NAME_20("Милена"),
  FEM_NAME_21("Маргарита"),
  FEM_NAME_22("Диана"),
  FEM_NAME_23("Ульяна"),
  FEM_NAME_24("Алёна"),
  FEM_NAME_25("Ангелина"),
  FEM_NAME_26("Анжелика"),
  FEM_NAME_27("Кристина"),
  FEM_NAME_28("Юлия"),
  FEM_NAME_29("Кира"),
  FEM_NAME_30("Ева"),
  FEM_NAME_31("Карина"),
  FEM_NAME_32("Василиса"),
  FEM_NAME_33("Василина"),
  FEM_NAME_34("Ольга"),
  FEM_NAME_35("Татьяна"),
  FEM_NAME_36("Ирина"),
  FEM_NAME_37("Таисия"),
  FEM_NAME_38("Евгения"),
  FEM_NAME_39("Яна"),
  FEM_NAME_40("Янина"),
  FEM_NAME_41("Вера"),
  FEM_NAME_42("Марина"),
  FEM_NAME_43("Елена"),
  FEM_NAME_44("Надежда"),
  FEM_NAME_45("Светлана"),
  FEM_NAME_46("Злата"),
  FEM_NAME_47("Олеся"),
  FEM_NAME_48("Алеся"),
  FEM_NAME_49("Наталья"),
  FEM_NAME_50("Наталия"),
  FEM_NAME_51("Эвелина"),
  FEM_NAME_52("Лилия"),
  FEM_NAME_53("Элина"),
  FEM_NAME_54("Виолетта"),
  FEM_NAME_55("Виола"),
  FEM_NAME_56("Нелли"),
  FEM_NAME_57("Мирослава"),
  FEM_NAME_58("Любовь"),
  FEM_NAME_59("Альбина"),
  FEM_NAME_60("Владислава"),
  FEM_NAME_61("Камилла"),
  FEM_NAME_62("Марианна"),
  FEM_NAME_63("Марьяна"),
  FEM_NAME_64("Ника"),
  FEM_NAME_65("Ярослава"),
  FEM_NAME_66("Валентина"),
  FEM_NAME_67("Эмилия"),
  FEM_NAME_68("Майя"),
  FEM_NAME_69("Эльвира"),
  FEM_NAME_70("Снежана"),
  FEM_NAME_71("Влада"),
  FEM_NAME_72("Каролина"),
  FEM_NAME_73("Лидия"),
  FEM_NAME_74("Виталина"),
  FEM_NAME_75("Виталия"),
  FEM_NAME_76("Нина"),
  FEM_NAME_77("Есения"),
  FEM_NAME_78("Оксана"),
  FEM_NAME_79("Аделина"),
  FEM_NAME_80("Ада"),
  FEM_NAME_81("Лада"),
  FEM_NAME_82("Амелия"),
  FEM_NAME_83("Амалия"),
  FEM_NAME_84("Элеонора"),
  FEM_NAME_85("Антонина"),
  FEM_NAME_86("Людмила"),
  FEM_NAME_87("Галина"),
  FEM_NAME_88("Тамара"),
  FEM_NAME_89("Алла"),
  FEM_NAME_90("Жанна"),
  FEM_NAME_91("Инна"),
  FEM_NAME_92("Лея"),
  FEM_NAME_93("Серафима"),
  FEM_NAME_94("Анфиса"),
  FEM_NAME_95("Евангелина"),
  FEM_NAME_96("Агата"),
  FEM_NAME_97("Агафья"),
  FEM_NAME_98("Агафия"),
  FEM_NAME_99("Лариса");

  private String name;

  FemaleName(String name) {

    this.name = name;
  }

  public String getName() {

    return name;
  }

  public static String getFemaleName() {

    return values()[(int) (Math.random() * values().length)].getName();
  }
}
